/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administer.users;

import view.controller.administer.users.ControllerPreviewUsers;

/**
 *
 * @author Djordje Gligorijevic
 */
public class PnlPreviewUsers extends javax.swing.JPanel {
    private ControllerPreviewUsers controllerPreviewUsers;
    /**
     * Creates new form PnlPreviewUsers
     */
    public PnlPreviewUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Nacrtaj nesto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controllerPreviewUsers
     */
    public ControllerPreviewUsers getControllerPreviewUsers() {
        return controllerPreviewUsers;
    }

    /**
     * @param controllerPreviewUsers the controllerPreviewUsers to set
     */
    public void setControllerPreviewUsers(ControllerPreviewUsers controllerPreviewUsers) {
        this.controllerPreviewUsers = controllerPreviewUsers;
    }
}
